flows:
  - "auth/*"
  - "routes/*"
executionOrder:
  flowsOrder:
    - "auth/LoginWithFixedUser.yaml"
    - "routes/IniatilizeAutomaticRoute.yaml"
includeTags:
  - auth
  - routes
excludeTags:
  - optional
